//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.03 at 04:34:03 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psychometrics.com/webservices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hello.wsdl;
