//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.03 at 04:34:03 PM MST 
//


package hello.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testPart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testPart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timeLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minComplete" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemPool" type="{http://psychometrics.com/webservices}itemPool"/>
 *         &lt;element name="testPartText" type="{http://psychometrics.com/webservices}testPartText" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testPart", propOrder = {
    "partId",
    "position",
    "timeLimit",
    "minComplete",
    "partName",
    "itemPool",
    "testPartText"
})
public class TestPart {

    protected int partId;
    protected int position;
    protected int timeLimit;
    protected int minComplete;
    @XmlElement(required = true)
    protected String partName;
    @XmlElement(required = true)
    protected ItemPool itemPool;
    @XmlElement(required = true)
    protected List<TestPartText> testPartText;

    /**
     * Gets the value of the partId property.
     * 
     */
    public int getPartId() {
        return partId;
    }

    /**
     * Sets the value of the partId property.
     * 
     */
    public void setPartId(int value) {
        this.partId = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

    /**
     * Gets the value of the timeLimit property.
     * 
     */
    public int getTimeLimit() {
        return timeLimit;
    }

    /**
     * Sets the value of the timeLimit property.
     * 
     */
    public void setTimeLimit(int value) {
        this.timeLimit = value;
    }

    /**
     * Gets the value of the minComplete property.
     * 
     */
    public int getMinComplete() {
        return minComplete;
    }

    /**
     * Sets the value of the minComplete property.
     * 
     */
    public void setMinComplete(int value) {
        this.minComplete = value;
    }

    /**
     * Gets the value of the partName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartName() {
        return partName;
    }

    /**
     * Sets the value of the partName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartName(String value) {
        this.partName = value;
    }

    /**
     * Gets the value of the itemPool property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPool }
     *     
     */
    public ItemPool getItemPool() {
        return itemPool;
    }

    /**
     * Sets the value of the itemPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPool }
     *     
     */
    public void setItemPool(ItemPool value) {
        this.itemPool = value;
    }

    /**
     * Gets the value of the testPartText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testPartText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestPartText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestPartText }
     * 
     * 
     */
    public List<TestPartText> getTestPartText() {
        if (testPartText == null) {
            testPartText = new ArrayList<TestPartText>();
        }
        return this.testPartText;
    }

}
